<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('All stylists'); ?> </h1>
</div>
<ul class="mp_all_stylists_container f-left" border="0" cellspacing="0" cellpadding="0">
    <?php
    //Get stylist data collection
    $stylist_collection = $this->getCollection();
    $stylist_count = count($stylist_collection);
    if ($stylist_count > 0) {
        foreach ($stylist_collection as $_stylist_collection) {
            $stylist_id = $_stylist_collection['entity_id'];
            $get_requestPath = Mage::helper('stylisthub/stylisthub')->getStylistRewriteUrl($stylist_id);
            if (strpos($_stylist_collection['store_logo'], '.') && $_stylist_collection['store_title'] != '') {
                ?>                    
                <li class="f-left">
                    <a class="mp_all_stylists_view" href="<?php echo $get_requestPath; ?>" title="<?php echo $_stylist_collection['store_title']; ?>">
                        <img src="<?php echo Mage::getBaseUrl('media') . "stylisthub/resized/" . $_stylist_collection['store_logo']; ?>" style="vertical-align: middle;" height="62" /> 
                    </a>
                </li>
        <?php } elseif (!strpos($_stylist_collection['store_logo'], '.') && $_stylist_collection['store_title'] != '') { ?>
                <li class="f-left">
                    <a class="mp_all_stylists_view" href="<?php echo $get_requestPath; ?>" title="<?php echo $_stylist_collection['store_title']; ?>">
                        <img src="<?php echo Mage::getBaseUrl('skin') . "frontend/default/market_place/stylisthub/images/image.jpg"; ?>"style="vertical-align: middle;" height="62" />
                    </a> 
                </li>
        <?php }
    } ?> 
    </ul>
    <div style="clear: both;"></div>  
    <?php
    echo $this->getPagerHtml();
} else {
    echo $this->__('There is no stylist(s) to show');
}
?>