<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */

/**
 * get stylist id
 */
$id = $this->getRequest()->getParam('id');
$vacationMode = Mage::getModel('stylisthub/vacationmode')->load($id,'stylist_id');
$vacationStatus = $vacationMode->getVacationStatus();
$current_url = Mage::helper('core/url')->getCurrentUrl();
$currentDate = Mage::getModel('core/date')->date('Y-m-d');

//display product collection
$stylist_page = Mage::getModel('stylisthub/stylistprofile')->collectprofile($id);?>

<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id))
            return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=439794342797425";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<div class="market_place_profile">
    <div class="markeft_place_main_widget">               
  <?php if ($vacationStatus==0){
  $vacationMessageData	= $vacationMode->getVacationMessage();
  if (!empty($vacationMessageData)){
  	?>      
  <h1><marquee><?php echo $vacationMessageData; ?></marquee></h1> 
  <?php }} ?>     
<?php //Face book Like Button Script  ?>
        <div id="fb-root"></div>           
        <!--display stylist logo-->
        <div class="mp_profiles_container">            
                <p class="mp_profiles_logo">
                    <?php if (strpos($stylist_page->getStoreLogo(), '.')) { ?>
                        <img src="<?php echo Mage::getBaseUrl('media') . "stylisthub/resized/" . $stylist_page->getStoreLogo(); ?>" alt="store logo" class="market_place_store_img" />                        
                    <?php } else { ?>
                        <h1><?php echo $stylist_page->getStoreTitle(); ?></h1>
                        <?php 
                     } ?>
                </p>
                <div class="stylists_store_info">
                <span class="all_review_container_wr"> 
                                <h3><?php echo $this->__('Average Ratings'); ?></h3> 
                                <?php $reviewCount = $this->reviewCount($id);?>
                                 <?php if($reviewCount>0){?>
                                <span class="all_reviews_details_wr"> 
                                    <p class="all_reviews_block">                                    
                                        <?php
                                        $ratingCollection = $this->averageRatings($id);
                                        if ($ratingCollection == 1) {
                                            ?>
                                            <label class="all_review_rating" style="width:20%;"></label>
                                        <?php } elseif ($ratingCollection == 2) { ?>
                                            <label class="all_review_rating" style="width:40%;"></label>
                                        <?php } elseif ($ratingCollection == 3) { ?>
                                            <label class="all_review_rating" style="width:60%;"></label>
                                        <?php } elseif ($ratingCollection == 4) { ?>
                                            <label class="all_review_rating" style="width:80%;"></label>
                                        <?php } else { ?>
                                            <label class="all_review_rating" style="width:100%;"></label>
                                        <?php } ?>                                       
                                    </p>                                                                        
                                </span>
                                 
                                <p class="rating_s"><?php echo $ratingCollection;?><?php echo $this->__(' based on ');?><?php echo $reviewCount; ?><?php echo $this->__(' rating[s]');?></p> 
        						<?php } else { ?>
        							
        					 <span class="all_reviews_details_wr"> 
                                    <p class="all_reviews_block"> 
                                     <label class="all_review_rating" style="width:0%;"></label>
                                        </p>                                                                        
                                </span>   
                                </span>      
        					<?php } ?>
                <div class="page-title stylists_store">                   
                    <?php //Face book Like Button  ?>
                    <div class="fb-like mp_fb_like_btn" data-href="<?php echo $current_url; ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
                <?php
                $fbImage = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/market_place/stylisthub/images/shareb.jpg';
                $fbUrl = 'http://www.facebook.com/sharer.php?s=100' . '&p[url]=' . $current_url . '&p[images][0]=' . Mage::getBaseUrl('media') . "stylistimage/" . $stylist_page->getStoreBanner() . '&p[title]=' . $stylist_page->getStoreTitle() . '&p[summary]=' . strip_tags($stylist_page->getDescription());
                ?>
                   
                    <a class="mp_social_network" target="_blank" href="<?php echo $fbUrl; ?>"><img src="<?php echo $fbImage ?>" title="<?php echo $this->__('Share with Facebook'); ?>" alt="<?php echo $this->__('Share with Facebook'); ?>" /></a>

                <?php //Google Share Button
                $googleImage = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/market_place/stylisthub/images/gplus.png';
                ?>
                   
                    <a class="mp_social_network" href="https://plus.google.com/share?url=<?php echo $current_url; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');
                        return false;" title="<?php echo $this->__('Share with Google+'); ?>">
                        <img src="<?php echo $googleImage; ?>" alt="<?php echo $this->__('Share with Google+'); ?>" />
                    </a>
                </div> 
                    <?php $collection = Mage::getModel('customer/customer')->load($id); ?>
                   
                </div>
                <p class="mp_profiles_desc"><?php echo $stylist_page->getDescription(); ?></p>
    </div>
    <?php
    //Display Reviews and Ratings
    $displayStylist  = Mage::getModel('stylisthub/stylistreview')->displayReview($id);
    $first_star     = $second_star = $third_star = $fourth_star = $fifth_star = $advanced_total = $ratingbar_color = 0;
   
    // ITERATING ALL RATINGS
    $advanced_total=0;
    foreach ($displayStylist as $individual_star) {
        $advanced_total = $advanced_total + 1;
        if ($individual_star['rating'] == 1) {
            $first_star = $first_star + 1;
        } elseif ($individual_star['rating'] == 2) {
            $second_star = $second_star + 1;
        } elseif ($individual_star['rating'] == 3) {
            $third_star = $third_star + 1;
        } elseif ($individual_star['rating'] == 4) {
            $fourth_star = $fourth_star + 1;
        } elseif($individual_star['rating'] == 5) {
            $fifth_star = $fifth_star + 1;
        }
    }
    
    // CALCULATING INDIVIDUAL RATINGS       
    $advanced_one   = ($first_star / $advanced_total) * 100;
    $advanced_two   = ($second_star / $advanced_total) * 100;
    $advanced_three = ($third_star / $advanced_total) * 100;
    $advanced_four  = ($fourth_star / $advanced_total) * 100;
    $advanced_five  = ($fifth_star / $advanced_total) * 100;
    ?>      
    <div class="individual-star-ratings">
        <h3><?php echo $this->__('Feedback Ratings'); ?> </h3>
        <ul class="rating-histogram">
            <li class="advanced-font-small"><span><?php echo $this->__('5 Stars'); ?></span>
                <div class="rating-bars">
                    <div class="progress  " style="width:<?php echo ceil($advanced_five); ?>%; background-color: <?php echo '#' . $ratingbar_color; ?> !important;"></div>
                </div> &nbsp;<strong><?php echo $fifth_star; ?> </strong>
            </li>
            <li class="advanced-font-small"><span><?php echo $this->__('4 Stars'); ?></span>
                <div class="rating-bars">
                    <div class="progress  " style="width:<?php echo ceil($advanced_four); ?>%; background-color: <?php echo '#' . $ratingbar_color; ?> !important;"></div>
                </div> &nbsp;<strong><?php echo $fourth_star; ?> </strong>
            </li>
            <li class="advanced-font-small"><span><?php echo $this->__('3 Stars'); ?></span>
                <div class="rating-bars">
                    <div class="progress  " style="width:<?php echo ceil($advanced_three); ?>%; background-color: <?php echo '#' . $ratingbar_color; ?> !important;"></div>
                </div> &nbsp;<strong><?php echo $third_star; ?> </strong>
            </li>
            <li class="advanced-font-small"><span><?php echo $this->__('2 Stars'); ?></span>
                <div class="rating-bars">
                    <div class="progress  " style="width:<?php echo ceil($advanced_two); ?>%; background-color: <?php echo '#' . $ratingbar_color; ?> !important;"></div>
                </div> &nbsp;<strong><?php echo $second_star; ?> </strong>
            </li>
            <li class="advanced-font-small"><span><?php echo $this->__('1 Stars'); ?></span>
                <div class="rating-bars">
                    <div class="progress  " style="width:<?php echo ceil($advanced_one); ?>%; background-color: <?php echo '#' . $ratingbar_color; ?> !important;"></div>
                </div> &nbsp;<strong><?php echo $first_star; ?> </strong>
            </li>
        </ul>

        <div class="positive_review_ratings">            
            <div class="positive_review_positive"><?php echo $this->__('Positive'); ?></div>
            <div class="positive_review_neutral"><?php echo $this->__('Neutral'); ?></div>
            <div class="positive_review_negative"><?php echo $this->__('Negative'); ?></div>
        </div>      	
                               
        <div class="customer_review">
        <?php
        // Get Reviews and Ratings 
        $review_count = Mage::helper('stylisthub/stylisthub')->getallreviewdata($id);
        if (count($review_count) > 0) { 
            $customer_id = $product_id = '';?>            
            <a class="mp_view_all" href='<?php echo $this->getAllreview($customer_id, $id, $product_id); ?>'> <?php echo $this->__('View all Reviews'); ?> </a>
            <br />      
        <?php        }
        if (Mage::getStoreConfig('stylisthub/stylist_review/enable_review')) {
            if (Mage::getSingleton('customer/session')->isLoggedIn()) {
                $customer_id    = Mage::getSingleton('customer/session')->getId();
                $orders         = Mage::helper('stylisthub/stylisthub')->allowReview($customer_id);
                $order_id       = $orders->getFirstItem()->getId();
                $end_date       = $orders->getFirstItem()->getCreatedAt();
                $current_date   = Mage::getModel('core/date')->date('Y-m-d H:i:s');
                $days           = abs(strtotime($current_date) - strtotime($end_date));
                $years          = floor($days / (365*60*60*24));
                $months         = floor(($days - $years * 365*60*60*24) / (30*60*60*24));
                $diff           = floor(($days - $years * 365 * 60 * 60 * 24 - $months * 30 * 60 * 60 * 24) / (60 * 60 * 24));
                $order          = Mage::getModel('sales/order')->load($order_id);
                $items          = $order->getAllItems();
                $getitem        = array_slice($items, -1, 1, true);
                foreach ($getitem as $item) {
                    $product_id     = $item->getProductId();
                    $products       = Mage::getModel('catalog/product')->load($product_id);
                    $product_stylist = $products->getStylistId();                   
                    $checkReview    = Mage::getModel('stylisthub/stylistreview')->checkReview($customer_id, $id, $product_id);
                    if ($diff <= 30 && $product_stylist == $id && $checkReview == '') {
                        ?>
                         <a href='<?php echo $this->getAllreview($customer_id, $id, $product_id) . '#stylist_review'; ?>'> <?php echo $this->__('Write a Review to this Stylist'); ?> </a> 
                        </p>
            <?php
            }
        }
    } else { ?>       
                <div>
                    <h6><?php echo $this->__('Have you bought something from this stylist?'); ?> </h6>
                    <a class="mp_view_allreview" href='<?php echo $this->loginUrl(); ?>'> <?php echo $this->__('Login to Review'); ?> </a>
               </div><br />
    <?php }
} ?>
    </div>        
    </div>        
    <div class="clear"></div>
    <?php  $display_product_count = $this->getCollection();
    $count_product = count($display_product_count);
    if($count_product>0){ ?>
<h2  class="pdct_name home_pdt_name"><span><?php echo $this->__('All Products'); ?></span>
    <?php } //Display stylist category and products   ?>
    <div class="toolbar">
<?php
$cat_ids_value          = array();
$display_cat_product    = $this->getRequest()->getParam('category_name');
$sort_product           = $this->getRequest()->getParam('sorting');
$stylist_value           = $this->stylistproduct($id);
foreach ($stylist_value as $_value) {
    if (!in_array($_value['category_id'], $cat_ids_value)) {
        $cat_ids_value[] = $_value['category_id'];
    }
}
//echo $this->getPagerHtml();
?>
 <?php $displayProduct = $this->getCollection();
        if (count($displayProduct)>0) { ?>
        <div class="sorter">
            <form name="category_products" id="mp_category_products" action="" method="post"> 
                <select name="category_name" onchange="this.form.submit();">
                    <option value="0" <?php if ($display_cat_product == 0) { ?>selected="selected" <?php } ?>> <?php echo $this->__('Select One Category'); ?></option>
                        <?php
                        foreach ($cat_ids_value as $category) {
                            $cat = Mage::getModel('catalog/category');
                            $cat->load($category);
                            ?>   
                        <option value=" <?php echo $category; ?>" <?php if ($display_cat_product == $category) { ?>selected="selected" <?php } ?> > <?php echo $cat->getName(); ?></option>
                    <?php } ?>
                </select>
                <select name="sorting" onchange="this.form.submit();" id="sorting">
                    <option value="name" <?php if ($sort_product == 'name') { ?>selected="selected" <?php } ?>><?php echo $this->__('Name'); ?></option>

                    <option value="price" <?php if ($sort_product == 'price') { ?>selected="selected" <?php } ?>><?php echo $this->__('Price'); ?></option>
                </select>
            </form>
        </div>
        <?php } ?>
        </div> 
    </h2>
    <ul class="products-grid product_snipt f-left">       
        <?php
        $displayProduct = $this->getCollection();
        if (!empty($displayProduct)) {
            foreach ($displayProduct as $_product) {
                $wordsCount_category = strlen($_product->getName()); ?>                
                <li class="item">
                    <a href="<?php echo $_product->getProductUrl(); ?>">
                        <img class="product-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(183); ?>" width="183" height="183" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <h2 class="product-name">
                        <a href="<?php echo $_product->getProductUrl(); ?>"> 
                            <?php if ($wordsCount_category > 15) { 
                                echo substr($this->htmlEscape($_product->getName()), 0, 15) . '...';
                                } else {
                                echo $_product->getName();
                             } ?>
                        </a>
                    </h2> 
                    <span class="regular-price">             
                        <span class="price">
                            <?php
                            //Display Product Price
                            $price          = $_product->getPrice();
                            $spl_price      = $_product->getSpecialPrice();
                            $dealExpireDate = $_product->getspecial_to_date();
                            if (!empty($spl_price) && ($dealExpireDate != '') && ($dealExpireDate >= $currentDate)) { ?>
                              <p><?php  echo '<del>' . Mage::helper('core')->currency($price, true, false) . '</del>'; ?></p>
                               <p><?php echo Mage::helper('core')->currency($spl_price, true, false); ?></p>
                            <?php } else { ?>
                              <p> <?php echo Mage::helper('core')->currency($price, true, false); ?></p>
                          <?php  }
                            ?>
                        </span>
                    </span>
                </li>
                        <?php   }
                    } else {
                        echo 'No products exists';
                    }    ?>
    </ul>
        <?php echo $this->getPagerHtml();

        //Display New products
                $enable_new = Mage::getStoreConfig('stylisthub/admin_approval_stylist_registration/display_new');
                if ($enable_new == 1) {
                    $new_products = Mage::getModel('stylisthub/stylistprofile')->newproduct($id);
                    $new_count = count($new_products);
                    if ($new_count >= 1) { ?>
            <h2  class="pdct_name home_pdt_name"><span><?php echo $this->__('New Products'); ?></span></h2>
            <ul class="products-grid product_snipt">
            <?php
            //Display New Products of this stylist

            foreach ($new_products as $new) {
                $wordsCount_new = strlen($new->getName());
                ?>
                    <li class="item">
                        <a href="<?php echo $new->getProductUrl(); ?>">
                            <img class="product-image" src="<?php echo $this->helper('catalog/image')->init($new, 'thumbnail')->resize(183); ?>" width="183" height="183" alt="<?php echo $this->stripTags($this->getImageLabel($new, 'small_image'), null, true) ?>" />
                        </a>
                        <h2 class="product-name">
                            <a href="<?php echo $new->getProductUrl(); ?>"><?php if ($wordsCount_new > 15) { ?>
                                <?php echo substr($this->htmlEscape($new->getName()), 0, 15) . '...';
                                } else {
                                echo $new->getName();
                                } ?> 
                            </a>
                        </h2> 
                        <span class="regular-price">
                            <span class="price">
                            <?php       //Display Product Price
                            $new_price      = $new->getPrice();
                            $new_spl_price  = $new->getSpecialPrice();                            
                            if (!empty($spl_price) && ($dealExpireDate != '') && ($dealExpireDate >= $currentDate)) { ?>
                                <p><?php  echo '<del>' . Mage::helper('core')->currency($new_spl_price, true, false) . '</del>'; ?></p>
                                <p><?php echo Mage::helper('core')->currency($new_spl_price, true, false); ?></p>
                           <?php } else { ?>
                                <p><?php echo Mage::helper('core')->currency($new_price, true, false); ?></p>
                            <?php }
                            ?>
                            </span>
                        </span>
                    </li>
            <?php }
     } ?> 
        </ul>
  <?php
        }
        $enable_popular = Mage::getStoreConfig('stylisthub/admin_approval_stylist_registration/display_popular');
        if ($enable_popular == 1) {
            $popular_products = Mage::getModel('stylisthub/stylistprofile')->popularproduct($id);
            $popular_count = count($popular_products);
            if ($popular_count >= 1) {
                ?>
            <h2 class="pdct_name home_pdt_name"><span><?php echo $this->__('Popular Products'); ?></span> </h2>
            <!--Display Popular product-->
            <ul class="products-grid product_snipt">

            <?php foreach ($popular_products as $popular) {
                $wordsCount_popular = strlen($popular->getName());
                ?>
                    <li class="item">
                        <a href="<?php echo $popular->getProductUrl(); ?>">
                            <img class="product-image" src="<?php echo $this->helper('catalog/image')->init($popular, 'thumbnail')->resize(183); ?>" width="183" height="183" alt="<?php echo $this->stripTags($this->getImageLabel($popular, 'small_image'), null, true) ?>" />
                        </a>
                        <h2 class="product-name">
                        <a href="<?php echo $popular->getProductUrl(); ?>"><?php if ($wordsCount_popular > 15) { ?>
                        <?php echo substr($this->htmlEscape($popular->getName()), 0, 15) . '...';
                    } else {
                        echo $popular->getName();
                    } ?> </a>
                    </h2>
                        <span class="regular-price">
                            <span class="price">
                            <?php //Display Product Price
                            $price          = $popular->getPrice();
                            $spl_price      = $popular->getSpecialPrice();
                            $dealExpireDate = $popular->getspecial_to_date();
                            if (!empty($spl_price) && ($dealExpireDate != '') && ($dealExpireDate >= $currentDate)) { ?>
                              <p><?php  echo '<del>' . Mage::helper('core')->currency($price, true, false) . '</del>'; ?></p>
                              <p><?php echo Mage::helper('core')->currency($spl_price, true, false); ?></p>
                           <?php } else { ?>
                                <p><?php echo Mage::helper('core')->currency($price, true, false); ?></p>
                           <?php }
                            ?></span>
                        </span>
                    </li>
        <?php }
    } ?>
        </ul>
    <?php
}
//display stylist category
$enable_category = Mage::getStoreConfig('stylisthub/admin_approval_stylist_registration/display_categories');
if ($enable_category == 1) {
 
    $cat_ids = array();
    $value = $this->stylistproduct($id);
    $value_count = count($value);
    if($value_count>0){
    ?>
            <h2 class="pdct_name home_pdt_name"><span><?php echo $this->__('Categories'); ?></span></h2>
        <ul class="products-grid product_snipt f-left">
    <?php
    foreach ($value as $_value) {
        if (!in_array($_value['category_id'], $cat_ids)) {
            $cat_ids[] = $_value['category_id'];
        }
    }
    foreach ($cat_ids as $category) {
        $cat = Mage::getModel('catalog/category');
        $cat->load($category);
        $wordsCount_popular = strlen($cat->getName());
        ?>

                <li class="item"><a href="<?php echo $this->getCategoryUrl($category, $id); ?>" >

        <?php if ($cat->getThumbnail()) { ?>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/category/' . $cat->getThumbnail(); ?>" height=135 width=135 />
        <?php } else { ?>
                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/market_place/images/np_thumb2.gif'; ?>" height=135 width=135 />
        <?php }
        ?>
                        <h2 class="product-name"> 
                            
                            <a href="<?php echo $cat->getProductUrl(); ?>"><?php if ($wordsCount_popular > 15) { ?>
                        <?php echo substr($this->htmlEscape($cat->getName()), 0, 15) . '...';
                    } else {
                        echo $cat->getName();
                    } ?> </a>
                            </h2>
                    </a>
                </li>
    <?php }
    ?>
        </ul>
<?php } }?>
</div>
</div>
