<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */
?>
<div style="clear: both;"></div>
<div  class="linker_stylist">   
    <?php
    $active = Mage::getStoreConfig('stylisthub/admin_approval_stylist_registration/displayproductpage');
    if ($active == 1) {
        $stylistId      = Mage::registry('current_product')->getStylistId();
        $stylistData    = $this->stylistdisplay($stylistId);
        $showProfile   = $this->stylistprofiledisplay($stylistId);
        if ($showProfile == 1) {
            $targetPath = 'stylisthub/stylist/displaystylist/id/' . $stylistId;
            $mainUrlRewrite     = Mage::getModel('core/url_rewrite')->load($targetPath, 'target_path');
            $getRequestPath     = $mainUrlRewrite->getRequestPath();
            $getRequestPath    = Mage::getUrl($getRequestPath);
            ?>
            <?php echo $this->__('Stylist'); ?>: 
            <a href='<?php echo $getRequestPath; ?>' class="link_stylist"><?php echo $stylistData['store_title']; ?></a>
        <?php }
    } ?>
</div>
