<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */

if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
    $customerStatus = Mage::getSingleton('customer/session')->getCustomerstatus();
    $stylisthub_groupId = Mage::helper('stylisthub')->getGroupId();
    if ($groupId == $stylisthub_groupId && $customerStatus == 0) {      
       echo '<h3><i>'. $this->__('Admin Approval is required. Please wait until admin confirms your Stylist Account').'</i></h3>';
    } else {
 ?>
<div class="box-account box-info">
<p><?php echo $this->__('Turn in to a stylist today and enjoy some incredible benefits like adding logo to your profile page for better branding, setting up multiple products to improve conversions, etc.'); ?></p>
<p><?php echo $this->__('Click the button to become a Stylist'); ?></p>
 <form name="buyer-stylist" id="buyer-stylist" action="<?php echo $this->becomeAstylistUrl(); ?>">
 <div class="input-box">
            <input type="checkbox" id="privacy_policy" name="privacy_policy" value="1" title="<?php echo $this->__('I agree the Terms and Condition') ?>" class="checkbox required-entry"/>
            <label for="privacy_policy"><?php echo $this->__('I agree the Terms and Condition') ?> (<a href="<?php echo Mage::helper('cms/page')->getPageUrl(6) ?>" target="_blank"><?php echo $this->__('Terms and Condition'); ?></a>)</label>
        </div>
<button class="button" >
    <span>
        <span><?php echo $this->__('Become a Stylist') ?></span>
    </span>
</button>
 </form>
</div>
<?php }  } ?>
<script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('buyer-stylist', true);
        </script>