<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt 
 */
/**
 *  Including js file for text editor -->
 */
?>

<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>stylisthub/nicEdit.js" type="text/javascript"></script>
<?php
/**
 *  Initilize product types
 */
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
	$stylistId = Mage::getSingleton('customer/session')->getCustomer()->getId();
}
/**
 * Check stylist enable vacation mode or not
 */
$vacationMode = Mage::getModel('stylisthub/vacationmode')->load($stylistId,'stylist_id');
 
$selectedType = '';
$selectedProductType = array();
/**
 *  Initilize product types from admin
 */
$selectedType = Mage::helper('stylisthub')->getSelectedPrdouctType();
/**
 *  Assigning product types to array variale
 */
$selectedProductType = explode(",", $selectedType);

/**
 *  Initilize product custom options
 */
$productCustomOptionsEnable = 0;
/**
 * Get the Shippping type
 */
$shippingtypeId = Mage::helper('stylisthub/stylisthub')->getStylistShipping();
$stylistShippingAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $shippingtypeId);
$stylistShipping = array();
$selectCountry = '<option value="">' . $this->__('Select') . '</option>';
$selectShipping = '<option value="">' . $this->__('Select') . '</option>';
foreach ($stylistShippingAttribute->getSource()->getAllOptions() as $option) {
    $value = $option['value'];
    if ($value != '') {
        $stylistShipping[$value] = $option['label'];
        $selectShipping .= "<option value='" . $option['value'] . "'>" . $option['label'] . "</option>";
    }
}
/**
 *  Initilize product approval disabled
 */
$productApproval = 2;
$vacationStatus = $vacationMode->getVacationStatus();
$disableProducts = $vacationMode->getProductDisabled();
$productCustomOptionsEnable = Mage::helper('stylisthub')->getPrdouctCustomOptions();
if (Mage::helper('stylisthub')->getProductApproval() == 1 || $vacationStatus == '1' && $disableProducts == '1' ) {
    $productApproval = Mage::helper('stylisthub')->getProductApproval();
} else {
    /**
     *  Initilise product approval disabled
     */
    $productApproval = 2;
}

?>

<!-- Stylisthub wrapper -->
<div class="stylisthub-wrapper" id="stylisthub-wrapper">     
    <div class="page-title">
        <h1><?php echo $this->__('Add New Product'); ?></h1>
    </div>
    <form action="<?php echo $this->addProductAction(); ?>" method="post" id="add_new_product_form" enctype="multipart/form-data">    
        <!-- Stylisthub product type container -->
        <div class="fieldset stylisthub-product-type" <?php
        if (count($selectedProductType) <= 1) {
            echo 'style="display:none;"';
        }
        ?>>
            <h4 class="legend"><?php echo $this->__('Product Type'); ?></h4>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="product_type"><?php echo $this->__('Product Type'); ?></label>
                        <div class="input-box">
                            <select id="product_type" name="type" title="<?php echo $this->__('Product Type'); ?>" class="select validate-select" onchange="changeProductType(this.value)">
                                <?php foreach ($selectedProductType as $value) { ?>
                                    <option value="<?php echo $value; ?>"><?php
                                        $productTypeCaps = $this->__($value);
                                        echo ucfirst($productTypeCaps);
                                        ?></option>    
                                <?php } ?>  
                            </select> 
                        </div>
                    </div>
                </li>
            </ul>
        </div> 

        <!-- Setting Simple product as default -->
        <?php if ($selectedType == '') {
            ?>
            <input type="hidden" id="default_product_type" name="type" value="simple">
        <?php } ?>

        <!-- Stylisthub category type container -->
        <?php
        $rootcatId = $categories = '';
        $rootcatId = Mage::app()->getStore()->getRootCategoryId();
        $categories = Mage::getModel('catalog/category')->getCategories($rootcatId);
        ?>
        <div class="fieldset stylisthub-category-type" <?php
        if (count($categories) < 1) {
            echo 'style="display:none;"';
        }
        ?> >
            <h4 class="legend"><?php echo $this->__('Product Categories'); ?></h4>    
            <div class="block-category">
                <?php
                if (!empty($categories)) {
                    echo $this->show_categories_tree($categories);
                }
                ?>
            </div>   
        </div>
        <!-- Stylisthub product general information container -->
        <div class="fieldset stylisthub-general">
            <h4 class="legend"><?php echo $this->__('General'); ?></h4>
            <ul class="form-list">
                <li class="fields wide">
                    <div class="field">
                        <label for="name" class="required"> <em>*</em> <?php echo $this->__('Name'); ?></label>
                        <div class="input-box">
                            <input id="name" name="product[name]" value="" class="required-entry input-text" type="text">
                        </div>
                    </div>

                </li>

                <li class="wide fields">
                    <div class="field">
                        <label for="description" class="required"> <em>*</em> <?php echo $this->__('Description'); ?> </label>    
                        <div class="input-box"><textarea id="description" name="product[description]" class="required-entry textarea" rows="2" cols="15"></textarea> </div>

                    </div>
                </li>
                <li class="wide fields">
                    <div class="field">
                        <label for="short_description" class="required"> <em>*</em> <?php echo $this->__('Short Description'); ?> </label>    
                        <div class="input-box"><textarea id="short_description" name="product[short_description]" class="required-entry textarea" rows="2" cols="15"></textarea> </div>
                    </div>
                </li>

                <li class="wide fields"> <div class="field" id="stylisthub_weight_div"  <?php
                    if (!in_array("simple", $selectedProductType) && $selectedType != '') {
                        echo 'style="display:none;"';
                    }
                    ?>>
                        <label for="weight" class="required"> <em>*</em> <?php echo $this->__('Weight'); ?></label>
                        <div class="input-box"><input id="weight" name="product[weight]" value="" class="required-entry validate-number validate-zero-or-greater validate-number-range number-range-0-99999999.9999 input-text" type="text" <?php
                            if (!in_array("simple", $selectedProductType) && $selectedType != '') {
                                echo 'disabled="disabled"';
                            }
                            ?>></div>
                    </div>
                </li>
                <li class="wide fields stylisthub_addnew_sku">
                    <div class="field">
                        <label for="sku" class="required"> <em>*</em> <?php echo $this->__('SKU'); ?> </label>    
                        <div class="input-box">
                       
                       
                            <input id="sku" name="product[sku]" value="" class="required-entry input-text" type="text"/>
                             <div id="category-loading" style="display: none">
					<img
						src="<?php echo Mage::getBaseUrl('skin') . 'frontend/default/market_place/images/ajax-loader-green.gif' ?>" />
				</div>
                            <span id="empty-text" style="display:none"><?php echo $this->__('Field Should Not Empty'); ?></span>
                            <span id="available" style="display:none"><?php echo $this->__('SKU Available'); ?></span >
                            <span id="not-available" style="display:none"><?php echo $this->__('SKU Not Available'); ?></span >
                        </div>
                    </div>
                </li>
                <?php if (Mage::getStoreConfig('stylisthub/product/set_banner') == 1) { ?>
                    <li class="wide fields">
                        <div class="field">
                            <label for="setbanner"> <?php echo $this->__('Display Product in Homepage Banner') ?></label>                   
                            <input type="checkbox" name="product[setbanner]" id="setbanner" value="1" />       
                        </div>
                    </li>
                <?php } ?>
            </ul>


        </div> 
        <!-- Stylisthub product price information container -->
        <div class="fieldset stylisthub-price">
            <h4 class="legend"><?php echo $this->__('Prices'); ?></h4>  
            <ul class="form-list">
                <li class="fields">

                    <label for="price" class="required"><?php echo $this->__('Price'); ?> <em>*</em></label>   
                    <div class="input-box" style="width: auto;"><input id="price" name="product[price]" value="" class="required-entry validate-zero-or-greater input-text" type="text">   
                        <strong>
                            [<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getBaseCurrencyCode())->getShortName(); ?>]
                        </strong>
                    </div>

                </li>
            </ul>
            <ul class="form-list">
                <li class="fields">     
                    <label for="special_price"><?php echo $this->__('Special Price'); ?></label>   
                    <div class="input-box" style="width: auto;"><input id="special_price" name="product[special_price]" value="" class="validate-zero-or-greater input-text" type="text">   
                        <strong>
                            [<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getBaseCurrencyCode())->getShortName(); ?>]
                        </strong>
                    </div>                    
                </li>
                <li class="fields">
                    <label for="special_from_date"><?php echo $this->__('Special Price From Date'); ?></label>
                    <div class="input-box" style="width: auto;">
                        <input name="product[special_from_date]" id="special_from_date" value="" class="validate-date validate-date-range date-range-date-from" type="text"/> 
                        <img src="<?php echo $this->getSkinUrl("images/calendar.gif"); ?>" alt="" class="v-middle" id="special_from_date_trig" title="<?php echo $this->__('Select Date'); ?>" style="" /> 
                    </div>
                </li>

                <li class="fields">
                    <label for="special_to_date"><?php echo $this->__('Special Price To Date'); ?></label>
                    <div class="input-box" style="width: auto;">
                        <input name="product[special_to_date]" id="special_to_date" value="" class="validate-date validate-date-range date-range-date-to" type="text" /> 
                        <img src="<?php echo $this->getSkinUrl("images/calendar.gif"); ?>" alt="" class="v-middle" id="special_to_date_trig" title="<?php echo $this->__('Select Date'); ?>" style="" /> 
                    </div>
                </li>                                       
            </ul>
        </div> 
        <!-- Stylisthub stylist shipping information container -->
        <div id="stylisthub_shipping" class="fieldset stylisthub-shipping">
            <h4 class="legend"><?php echo $this->__('Shipping'); ?></h4>
            <ul class="form-list">
                <li class="fields">
                    <label for="default_country" class="required"><em>*</em><?php echo $this->__('Select Default Country'); ?></label>
                    <div class="input-box">
                        <select id="default_country" name="product[default_country]"  class="select select input-text required-entry input-text_pro">
                            <?php
                            $collection = Mage::getModel('directory/country')->getCollection();
                            foreach ($collection as $country) {
                                $countryId = $country->getId();
                                $countryName = $country->getName();
                                $selectCountry .= '<option value="' . $countryId . '">' . $countryName . '</option>';                               
                            }
                            echo $selectCountry;
                            ?>   
                        </select>                      
                    </div>
                </li>
                <li class="fields">
                    <label for="stylist_shipping" class="required"><em>*</em><?php echo $this->__('Select Shipping'); ?></label>
                    <div class="input-box">
                        <select id="stylist_shipping" name="product[stylist_shipping_option]"  class="select select input-text required-entry input-text_pro">
                            <?php echo $selectShipping; ?>
                        </select>                      
                    </div>
                </li>
                <li class="fields" id="shipping_price" style="display:none">
                    <label for="national_shipping_price" class="required"><em>*</em><?php echo $this->__('National Shipping Price'); ?></label>
                    <div class="input-box">
                        <input id="national_shipping_price" name="product[national_shipping_price]" value="" class="required-entry validate-zero-or-greater input-text" type="text" >                         
                    </div>                   
                    <label for="international_shipping_price" class="required"><em>*</em><?php echo $this->__('International Shipping Price'); ?></label>
                    <div class="input-box">
                        <input id="international_shipping_price" name="product[international_shipping_price]" value="" class="required-entry validate-zero-or-greater input-text" type="text" >                         
                    </div>
                </li>
            </ul>
            <div class="clear"></div>
        </div>

        <!-- Stylisthub product image information container -->
        <div class="fieldset stylisthub-image">
            <h4 class="legend"><?php echo $this->__('Images'); ?></h4>
            <ul class="form-list">
                <li class="fields">
                    <button class="button" type="button" onclick="addNewImage();"> <span><span> + <?php echo $this->__('Add Image'); ?></span></span></button> 
                    <div id="stylisthub_image_list"></div>
                </li>
                 
            </ul>
            <div class="clear"></div>
        </div> 
        <!-- Stylisthub product meta information container -->
        <div class="fieldset stylisthub-meta-information">
            <h4 class="legend"><?php echo $this->__('Meta Information'); ?></h4>   
            <ul class="form-list">
                <li class="wide fields">
                    <div class="field">
                        <label for="meta_title"><?php echo $this->__('Meta Title'); ?></label>
                        <div class="input-box"><input id="meta_title" name="product[meta_title]" value="" class=" input-text" type="text"></div>
                    </div>
                </li>
            </ul>
            <ul class="form-list">
                <li class="fields">

                    <div class="field">
                        <label for="meta_keyword"><?php echo $this->__('Meta Keywords'); ?></label>
                        <div class="input-box"><textarea id="meta_keyword" name="product[meta_keyword]" class=" textarea" rows="2" cols="15"></textarea></div>
                    </div>
                    <div class="field">
                        <label for="meta_description"><?php echo $this->__('Meta Description'); ?></label>
                        <div class="input-box"><textarea id="meta_description" name="product[meta_description]" class="validate-length maximum-length-255 textarea" rows="2" cols="15"></textarea></div>
                        <p class="note"><?php echo $this->__('Maximum 255 chars'); ?></p></div>
                </li></ul>

        </div>       
        <!-- Stylisthub product inventory information container -->
        <div class="fieldset stylisthub-inventory">
            <h4 class="legend"><?php echo $this->__('Inventory'); ?></h4>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="inventory_qty" class="required"><em>*</em> <?php echo $this->__('Qty'); ?></label>    
                        <div class="input-box"><input type="text" class="input-text required-entry validate-number" id="inventory_qty" name="product[stock_data][qty]" value=""> </div>
                    </div>
                    <div class="field">  
                        <label for="inventory_stock_availability"><?php echo $this->__('Stock Availability'); ?></label>
                        <div class="input-box"><select id="inventory_stock_availability" name="product[stock_data][is_in_stock]" class="select">
                                <option value="1" selected="selected"><?php echo $this->__('In Stock'); ?></option>
                                <option value="0"><?php echo $this->__('Out of Stock'); ?></option>
                            </select></div>
                    </div> 
                </li>
            </ul>
        </div> 

        <!-- Compare price with selected product -->
        <div class="fieldset stylisthub-compareprice">
            <h4 class="legend"><?php echo $this->__('Compare Price by assigning existing product[s]'); ?></h4>
            <ul class="form-list">
                <li class="wide fields">
                    <div id="product-field" class="field">
                        <label for="compare-price"><?php echo $this->__('Enter Product Name'); ?></label>    
                        <div class="input-box"><input type="text" class="input-text" autocomplete="off" id="compare-price" name="compare_product" value=""/> 
                            <span id="indicator1" style="display: none">
                                <img src="<?php echo Mage::getBaseUrl('skin') . 'frontend/default/market_place/images/ajax-loader-green.gif' ?>" />
                            </span>
                             <span class="compare-note"><?php echo '<i>Add more than one products as comma separated. Ex: example,test</i>'?></span>
                            <input type="hidden" value="" id="product_compare_id" name="product[compare_product_id]"/>
                            <div id="autoCompleteMenu"></div>
                        </div>    
                    </div>

                </li>
            </ul>
        </div> 
        

        <!-- Stylisthub downloadable product information container -->
        <?php if (in_array("downloadable", $selectedProductType)) { ?> 

            <div id="stylisthub_downloadable_product_div" class="fieldset stylisthub-downloadable-products" 
            <?php
            if (in_array("downloadable", $selectedProductType) && count($selectedProductType) != 1) {
                echo 'style="display:none;"';
            }
            ?> >
                <h4 class="legend"><?php echo $this->__('Downloadable Information'); ?></h4>
                <ul class="form-list">
                    <li class="mp_dp_head"><?php echo $this->__('Samples'); ?></li>
                    <li class="fields mp_dp_fields">
                        <div class="headings">
                            <span class="label"><label for="name"><?php echo $this->__('Title'); ?></label>
                            </span>
                            <span class="value">
                                <input type="text" class="input-text" name="product[samples_title]" value="Samples">
                            </span>
                            <div class="clear"></div>
                            <!--<span class="scope-label">[<?php echo $this->__('STORE VIEW'); ?>]</span>       -->
                        </div>
                        <div class="stylisthub-sample" style="padding:0px;">
                            <table cellspacing="0" class="data border">
                                <thead>
                                    <tr class="headings">
                                        <th><label><?php echo $this->__('Title'); ?></label> <span class="required">*</span></th>
                                        <th><label><?php echo $this->__('File'); ?></label></th>
                                        <th><label class="nobr"><?php echo $this->__('Sort Order'); ?></label></th>
                                        <th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody id="sample_items_body"> 
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="100" class="a-right">
                                            <button id="add_sample_item" name="sample_items_body"  title="<?php echo $this->__('Add New Row'); ?>" type="button" class="button scalable add add-select-row" onclick="addMarketPlaceDownloadableSamplesRow(this.name)">
                                                <span><span><?php echo $this->__('Add New Row'); ?></span></span>
                                            </button>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>   
                        </div>                    
                    </li>
                    <li class="mp_dp_head"><?php echo $this->__('Download'); ?></li>
                    <li class="fields mp_dp_fields">
                        <div class="headings">
                            <span class="label"><label for="name"><?php echo $this->__('Title'); ?></label></span>
                            <span class="value"><input type="text" class="input-text" id="downloadable_links_title" name="product[links_title]" value="Download"></span>
                            <div class="clear"></div>
                            <span class="label"><label for="name"><?php echo $this->__('Links can be purchased separately'); ?></label></span>
                            <select name="product[links_purchased_separately]" id="downloadable_link_purchase_type" class="" title=""><option value="1"><?php echo $this->__('Yes'); ?></option><option value="0" selected="selected"><?php echo $this->__('No'); ?></option></select>
                            <div class="clear"></div>
                        </div>   
                        <!--[<?php echo $this->__('GLOBAL'); ?>]-->
                        <table width="100%" cellspacing="CCC">
                        <!--    <colgroup><col width="33%">
                            <col>
                            <col>
                            <col>
                            <col width="1">
                            <col width="1">
                            <col width="1">
                            <col width="1">
                            </colgroup>-->           

                            <tbody id="link_items_body">
                            </tbody> 
                            <tfoot>
                                <tr>
                                    <td colspan="8" class="a-right">
                                        <button id="add_link_item" class="button" title="Add New Row" type="button"  name="link_items_body" onclick="addMarketPlaceDownloadableLinksRow(this.name)">
                                            <span><span><span><?php echo $this->__('Add New Row'); ?></span></span></span></button></td>
                                </tr>
                            </tfoot>   
                        </table>
                    </li>
                </ul>
                <div class="clear"></div>
            </div> 
        <?php } ?>


        <!-- Stylisthub product custom options container -->
        <!-- If checking whether product custom options enabled or not -->
        <?php if ($productCustomOptionsEnable == 1) { ?>
            <div class="fieldset stylisthub-custom-option">
                <h4 class="legend"><?php echo $this->__('Custom Options'); ?></h4> 
                <!-- Custom option add button -->
                <div id="stylisthub_custom_option">
                    <button id="stylisthub_new_custom_option" class="button f-right right-button" type="button" onclick="addMarketPlaceCustomOption()"><span><span><?php echo $this->__('Add New Option'); ?></span></span></button>
                    <h3><?php echo $this->__('[GLOBAL]') ?></h3>
                </div>
                <!-- Displaying All options list -->
                <div id="stylisthub_custom_option_list"></div>
                <div  class="clear"></div>
            </div>
            <?php
        }
        /**
         *  End if for checking whether product option enabled or not    
         */
        ?>  <!-- Stylisthub product hidden fields container -->
        <div class="stylisthub-hidden-values">       
            <input type="hidden" name="product[website_ids][]" value="<?php echo $this->getWebsiteId(); ?>" id="product_website_1">
            <input type="hidden" id="visibility" name="product[visibility]" value="<?php echo Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH; ?>">
            <input type="hidden" id="attribute_set_id" name="set" title="<?php echo $this->__("Attribute Set"); ?>" value="<?php echo $this->getAttributeSetId(); ?>">
            <input type="hidden" id="status" name="product[status]" value="<?php
            if (isset($productApproval)) {
                echo $productApproval;
            }
            ?>">
            <input type="hidden" id="tax_class_id" name="product[tax_class_id]"  value="0">
            <input type="hidden" id="store" name="store"  value="<?php echo $this->getStoreId(); ?>">
        </div>
        <div class="buttons-set">
            <p class="required">* <?php echo $this->__('Required Fields') ?></p>
            <button class="button" onclick ="checkTextarea()" id="button" type="submit" title="<?php echo $this->__('Save Product') ?>" class="button"><span><span><?php echo $this->__('Save Product') ?></span></span></button>
        </div>
    </form>
</div>

<!-- Following div dynamically create custom options  -->
<div class="hidden-custom-option" style="display:none;">

    <div class="option-box" id="stylisthub_custom_option_YYY"> 
        <!-- Div for removing custom option -->
        <div class="dont-remove market_place_option-box">    
            <!-- Custom option table -->
            <table id="product_option_XXX" class="option-header form-list" cellpadding="0" cellspacing="0">
                <input type="hidden" id="product_option_XXX_is_delete" name="product[options][XXX][is_delete]" value="">
                <input type="hidden" id="product_option_XXX_previous_type" name="product[options][XXX][previous_type]" value="">
                <input type="hidden" id="product_option_XXX_previous_group" name="product[options][XXX][previous_group]" value="">
                <input type="hidden" id="product_option_XXX_id" name="product[options][XXX][id]" value="XXX">
                <input type="hidden" id="product_option_XXX_option_id" name="product[options][XXX][option_id]" value="0">
                <thead>
                    <tr>
                        <th class="opt-title"> <label class="required"><em>*</em> <?php echo $this->__('Title'); ?></label></th>
                        <th class="opt-type"> <label class="required"><em>*</em> <?php echo $this->__('Input Type'); ?></label></th>
                        <th class="opt-req"> <label> <?php echo $this->__('Is Required'); ?></label></th>
                        <th class="a-right"><button id="delete_product_option_XXX"  title="<?php echo $this->__('Delete Option'); ?>" type="button" class="button scalable delete delete-product-option " onclick="removeMarketPlaceCustomOption(this)" style=""><span><span><?php echo $this->__('Delete Option'); ?></span></span></button></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><input type="text" class="required-entry input-text" id="product_option_XXX_title" name="product[options][XXX][title]" value=""></td>
                        <td>
                            <select onchange="changeMarketPlaceCustomOption(this, XXX)" name="product[options][XXX][type]" id="product_option_XXX_type" class="select validate-select" title="">
                                <option value="">-- <?php echo $this->__('Please select'); ?> --</option>
                                <optgroup label="<?php echo $this->__('Text'); ?>">
                                    <option value="field"><?php echo $this->__('Field'); ?></option>
                                    <option value="area"><?php echo $this->__('Area'); ?></option>
                                </optgroup>
                                <optgroup label="<?php echo $this->__('File'); ?>">
                                    <option value="file"><?php echo $this->__('File'); ?></option>
                                </optgroup>
                                <optgroup label="<?php echo $this->__('Select'); ?>">
                                    <option value="drop_down"><?php echo $this->__('Drop-down'); ?></option>
                                    <option value="radio"><?php echo $this->__('Radio Buttons'); ?></option>
                                    <option value="checkbox"><?php echo $this->__('Checkbox'); ?></option>
                                    <option value="multiple"><?php echo $this->__('Multiple Select'); ?></option>
                                </optgroup>
                                <optgroup label="<?php echo $this->__('Date'); ?>">
                                    <option value="date"><?php echo $this->__('Date'); ?></option>
                                    <option value="date_time"><?php echo $this->__('Date'); ?> &amp; <?php echo $this->__('Time'); ?></option>
                                    <option value="time"><?php echo $this->__('Time'); ?></option>
                                </optgroup>
                            </select>
                        </td>
                        <td class="opt-req">
                            <select name="product[options][XXX][is_require]" id="product_option_XXX_is_require" class="select" title="">
                                <option value="1"><?php echo $this->__('Yes'); ?></option>
                                <option value="0"><?php echo $this->__('No'); ?></option>
                            </select>
                        </td>
                        <td>
                            <input type="text" class="validate-zero-or-greater input-text" name="product[options][XXX][sort_order]" value="" style="margin-right: 0;">
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!-- Custom option text  -->
    <div id="product_option_CCC_type_text" class="grid tier form-list">
        <table class="form-list border custom_option_text_field" cellpadding="0" cellspacing="0">
            <tbody>
                <tr class="headings">
                    <th class="type-price"> <label><?php echo $this->__('Price'); ?></label></th>
                    <th class="type-type"><label><?php echo $this->__('Price Type'); ?></label></th>
                    <th class="type-sku"><label><?php echo $this->__('SKU'); ?></label></th>
                    <th class="type-last last"><label><?php echo $this->__('Max Characters'); ?></label></th>
                </tr>
                <tr>
                    <td>
                        <input type="text" class="input-text validate-number product-option-price" id="product_option_CCC_price" name="product[options][CCC][price]" value="">
                    </td>
                    <td>
                        <select name="product[options][CCC][price_type]" id="product_option_CCC_price_type" class="select product-option-price-type" title="">
                            <option value="fixed"><?php echo $this->__('Fixed'); ?></option>
                            <option value="percent"><?php echo $this->__('Percent'); ?></option>
                        </select>
                    </td>
                    <td>
                        <input type="text" class="input-text" name="product[options][CCC][sku]" value="">
                    </td>
                    <td class="type-last last">
                        <input type="text" class="input-text validate-zero-or-greater" name="product[options][CCC][max_characters]" value="">
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- Custom option file -->
    <div id="product_option_CCC_type_file" class="grid tier form-list">
        <table class="border form-list mareket_place_price_table" cellpadding="0" cellspacing="0">
            <tbody><tr class="headings">
                    <th class="type-price"><label><?php echo $this->__('Price'); ?></label></th>
                    <th class="type-type"><label><?php echo $this->__('Price Type'); ?></label></th>
                    <th class="type-sku"><label><?php echo $this->__('SKU'); ?></label></th>
                    <th class="type-title"><label><?php echo $this->__('Allowed File Extensions'); ?></label></th>
                    <th class="last"><label><?php echo $this->__('Maximum Image Size'); ?></label></th>
                </tr>
                <tr>
                    <td>
                        <input class="input-text validate-zero-or-greater" type="text" name="product[options][CCC][price]" value="">
                    </td>
                    <td>
                        <select name="product[options][CCC][price_type]" id="product_option_CCC_price_type" class="select product-option-price-type" title="">    
                            <option value="fixed"><?php echo $this->__('Fixed'); ?></option>
                            <option value="percent"><?php echo $this->__('Percent'); ?></option>
                        </select>
                    </td>
                    <td>
                        <input type="text" class="input-text" name="product[options][CCC][sku]" value="">
                    </td>
                    <td>
                        <input class="input-text file_extension" type="text" name="product[options][CCC][file_extension]" value="">
                    </td>
                    <td class="type-last last" nowrap="">
                        <input class="input-text" type="text" name="product[options][CCC][image_size_x]" value=""> <?php echo $this->__('x'); ?>&nbsp;
                        <input class="input-text" type="text" name="product[options][CCC][image_size_y]" value=""><?php echo $this->__('px') . '.'; ?>
                        <br><?php echo $this->__('leave blank if its not an image'); ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>   
    <!-- Custom option date -->
    <div id="product_option_CCC_type_date" class="grid tier form-list" style="">
        <table class="border mareket_place_date_table" cellpadding="0" cellspacing="0">
            <tbody>
                <tr class="headings">
                    <th class="type-price"><?php echo $this->__('Price'); ?></th>
                    <th class="type-type"><?php echo $this->__('Price Type'); ?></th>
                    <th class="last"><?php echo $this->__('SKU'); ?></th>
                </tr>
                <tr>
                    <td>
                        <input type="text" class="input-text validate-number product-option-price" id="product_option_CCC_price" name="product[options][CCC][price]" value="">
                    </td>
                    <td>
                        <select name="product[options][CCC][price_type]" id="product_option_CCC_price_type" class="select product-option-price-type" title="">
                            <option value="fixed"><?php echo $this->__('Fixed'); ?></option>
                            <option value="percent"><?php echo $this->__('Percent'); ?></option>
                        </select>
                    </td>
                    <td class="last">
                        <input type="text" class="input-text type-sku" name="product[options][CCC][sku]" value="">
                    </td>
                </tr>
            </tbody>
        </table>
    </div>    
    <!-- Custom option select -->
    <div id="product_option_CCC_type_select" class="grid tier form-list">
        <table class="border market_place_dropdown_row form-list" cellpadding="0" cellspacing="0">
            <input type="hidden" class="required-option-select-type-rows" name="validation_CCC_result" value="">
            <thead>
                <tr class="headings">
                    <th class="type-title"> <label class="required"> <em>*</em> <?php echo $this->__('Title'); ?> </label>

                    </th>
                    <th class="type-price"> <label><?php echo $this->__('Price'); ?></label></th>
                    <th class="type-type"><label><?php echo $this->__('Price Type'); ?></label></th>
                    <th class="type-sku"><label><?php echo $this->__('SKU'); ?></label></th>
                    <th class="type-order"><label><?php echo $this->__('Sort Order'); ?></label></th>
                    <th class="type-butt last">&nbsp;</th>
                </tr>
            </thead>
            <tbody id="select_option_type_row_CCC"> 
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="100" class="a-right">
                        <button id="add_select_row_button_CCC" name="select_option_type_row_CCC" title="<?php echo $this->__('Add New Row'); ?>" type="button" class="button scalable add add-select-row" onclick="addMarketPlaceChildSelectOption(this.name, CCC)">
                            <span><span><?php echo $this->__('Add New Row'); ?></span></span>
                        </button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- Custom option select add row -->
    <table>    
        <tr id="product_option_CCC_select_AAA">
            <td>
                <input type="hidden" name="product[options][CCC][values][AAA][option_type_id]" value="-1">
                <input type="hidden" id="product_option_CCC_select_AAA_is_delete" name="product[options][CCC][values][AAA][is_delete]" value="">
                <input type="text" class="required-entry input-text select-type-title" id="product_option_CCC_select_AAA_title" name="product[options][CCC][values][AAA][title]" value="">
            </td>
            <td>
                <input type="text" class="input-text validate-number product-option-price" id="product_option_CCC_select_AAA_price" name="product[options][CCC][values][AAA][price]" value="">
            </td>
            <td>
                <select name="product[options][CCC][values][AAA][price_type]" id="product_option_CCC_select_AAA_price_type" class="select product-option-price-type" title="">
                    <option value="fixed"><?php echo $this->__('Fixed'); ?></option>
                    <option value="percent"><?php echo $this->__('Percent'); ?></option>
                </select>
            </td>
            <td>
                <input type="text" class="input-text" name="product[options][CCC][values][AAA][sku]" value="">
            </td>
            <td>
                <input type="text" class="validate-zero-or-greater input-text" name="product[options][CCC][values][AAA][sort_order]" value="">
            </td>
            <td class="last">
                <span title="Delete row">
                    <button id="delete_select_row_button" title="Delete Row" type="button" class="button scalable delete delete-select-row icon-btn" onclick="removeMarketPlaceChildSelectOption(this)" style="">
                        <span><span><?php echo $this->__('Delete Row'); ?></span></span></button></span>
            </td>
        </tr>
    </table>      
</div>

<!-- Dynamically downloadable products Sample, Links and Sample_links row -->
<table style="display:none;"> 
    <tr id="stylisthub_download_sample_row_CCC">
        <td>
            <input type="hidden" class="__delete__" name="downloadable[sample][CCC][is_delete]" value="">
            <input type="hidden" name="downloadable[sample][CCC][sample_id]" value="CCC">
            <input type="text" class="required-entry input-text" name="downloadable[sample][CCC][title]" value="">
        </td>
        <td>
            <div class="files-wide">
                <div class="stylisthub_row">
                    <label for="downloadable_sample_CCC_file_type">
                        <input type="radio" class="radio validate-one-required-by-name" id="downloadable_sample_CCC_file_type" name="downloadable[sample][CCC][type]" value="file" checked="checked">
                        <?php echo $this->__('File'); ?>:</label>
                    <input type="file" class="validate-downloadable-file" id="downloadable_sample_CCC_file_save" name="sample_CCC" value="">
                    <div id="downloadable_sample_CCC_file">
                        <div class="no-display" id="downloadable_sample_CCC_file-template">
                        </div>
                    </div></div>
                <div class="row">
                    <label for="downloadable_sample_CCC_url_type">
                        <input type="radio" class="radio validate-one-required-by-name" id="downloadable_sample_CCC_url_type" name="downloadable[sample][CCC][type]" value="url">
                        <?php echo $this->__('URL'); ?>:</label> <input type="text" class="validate-downloadable-url input-text" name="downloadable[sample][CCC][sample_url]" value="">
                </div>
                <div>
                    <span id="downloadable_sample_CCC_container"></span>
                </div>
            </div>
        </td>
        <td class="a-center">
            <input type="text" name="downloadable[sample][CCC][sort_order]" value="" class="input-text sort stylisthub_sort_order">
        </td>
        <td>
            <button onclick="removeMarketPlaceDownloadableSamplesRow(this)" type="button" class="button">
                <span><span><span><?php echo $this->__('Delete'); ?></span></span></span></button>
        </td>
    </tr>
</table> 

<!-- Dynamically downloadable products Links row -->
<table style="display:none;"> 
    <tr id="stylisthub_download_link_row_CCC">
        <td class="stylisthub_download_info_td">
            <table border="0" cellspacing="0" cellpadding="0" width="100%" class="stylisthub_download_info_table">
                <tr><th><label><?php echo $this->__('Title'); ?></label><span class="required">*</span></th><td>
                        <input type="hidden" class="__delete__" name="downloadable[link][CCC][is_delete]" value="">
                        <input type="hidden" name="downloadable[link][CCC][link_id]" value="CCC">
                        <input type="text" class="required-entry input-text" name="downloadable[link][CCC][title]" value="">
                    </td></tr>
                <tr><th><label><?php echo $this->__('Price'); ?></label></th><td class="input-price">
                        <input type="text" id="downloadable_link_CCC_price_value" class="input-text validate-number link-prices" name="downloadable[link][CCC][price]" value="0">
                        <p><label> [<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getBaseCurrencyCode())->getShortName(); ?>]</label></p>
                    </td></tr>
                <tr><th><label class="nobr"><?php echo $this->__('Max. Downloads'); ?></label></th><td>
                        <input type="text" id="downloadable_link_CCC_downloads" name="downloadable[link][CCC][number_of_downloads]" class="input-text downloads" value="0">
                        <p>
                            <input type="checkbox" class="checkbox" id="downloadable_link_CCC_is_unlimited" name="downloadable[link][CCC][is_unlimited]" value="1" <?php echo 'checked="checked"'; ?>>
                            <label for="downloadable_link_CCC_is_unlimited"><?php echo $this->__('Unlimited'); ?></label>
                        </p></td></tr>
                <tr><th><label><?php echo $this->__('Shareable'); ?></label></th><td><select id="downloadable_link _CCC_shareable" name="downloadable[link][CCC][is_shareable]">
                            <option value="1"><?php echo $this->__('Yes'); ?></option>
                            <option value="CCC"><?php echo $this->__('No'); ?></option>
                            <option value="2" selected="selected"><?php echo $this->__('Use config'); ?></option>
                        </select>
                    </td></tr>
                <tr><th><label><?php echo $this->__('Sample'); ?></label></th><td>
                        <div class="files-wide">
                            <div class="stylisthub_row">
                                <label for="downloadable_link_CCC_sample_file_type">
                                    <input type="radio" class="radio" id="downloadable_link_CCC_sample_file_type" name="downloadable[link][CCC][sample][type]" value="file">
                                    <?php echo $this->__('File'); ?>:</label>
                                <input type="file" class="validate-downloadable-file" id="downloadable_link_CCC_file_save" name="l_sample_CCC" value="">
                            </div><div class="row"><label for="downloadable_link_CCC_sample_url_type">
                                    <input type="radio" class="radio" id="downloadable_link_CCC_sample_url_type" name="downloadable[link][CCC][sample][type]" value="url">
                                    <?php echo $this->__('URL'); ?>:</label>
                                <input type="text" class="input-text" name="downloadable[link][CCC][sample][url]" value="">
                            </div>                         
                        </div>
                    </td></tr>
                <tr><th><label><?php echo $this->__('File'); ?></label></th><td>
                        <div class="files-wide">
                            <div class="stylisthub_row">
                                <label for="downloadable_link_CCC_file_type">
                                    <input type="radio" class="radio validate-one-required-by-name" id="downloadable_link_CCC_file_type" name="downloadable[link][CCC][type]" value="file" checked="checked">
                                    <?php echo $this->__('File'); ?>:
                                </label>
                                <input type="file" class="validate-downloadable-file" id="downloadable_sample_link_CCC_file_save" name="links_CCC" value="">
                            </div><div class="row">
                                <label for="downloadable_link_CCC_url_type">
                                    <input type="radio" class="radio validate-one-required-by-name" id="downloadable_link_CCC_url_type" name="downloadable[link][CCC][type]" value="url">
                                    <?php echo $this->__('URL'); ?>:</label><input type="text" class="validate-downloadable-url input-text" name="downloadable[link][CCC][link_url]" value="">
                            </div>
                        </div>
                    </td></tr>
                <tr><th><label class="nobr"><?php echo $this->__('Sort Order'); ?></label></th><td>
                        <input type="text" name="downloadable[link][CCC][sort_order]" value="" class="input-text sort"></td></tr>
                <tr><th>&nbsp;</th><td>
                        <button id="downloadable_link_CCC_delete_button" onclick="removeMarketPlaceDownloadableLinksRow(this);"  type="button" class="scalable button delete-link-item">
                            <span><span><span> <?php echo $this->__('Delete'); ?></span></span></span></button></td></tr>
            </table>
        </td>
    </tr>
</table> 
<script type="text/javascript">
                                function getSelectionId(text, li) {
                                    var id = li.id;
                                    var existing = $('product_compare_id').value;
                                    if (existing == '') {
                                        $('product_compare_id').value = id;
                                    } else {
                                        $('product_compare_id').value = existing + ',' + id;
                                    }
                                }
                                document.observe("dom:loaded", function() {
                                    var q = $('compare-price').getValue();
                                    new Ajax.Autocompleter(
                                            'compare-price',
                                            'autoCompleteMenu',
                                            '<?php echo Mage::getUrl('stylisthub/product/compareprice'); ?>',
                                            {paramName: "q", afterUpdateElement: getSelectionId, multiple: true, indicator: 'indicator1', tokens: ','}
                                    );
                                });
        </script>
<!-- Add product form validation -->
<script type="text/javascript">
                                var addProductForm = new VarienForm('add_new_product_form', true);
                                function changeProductType(value)
                                {
                                    if (value != 'simple') {
                                        $(weight).setAttribute('disabled', 'disabled');
                                        $(stylisthub_weight_div).hide();                                                               
                                    }
                                    else {
                                        $(weight).removeAttribute('disabled');
                                        $(stylisthub_weight_div).show();
                                    }
                                    if (value == 'downloadable') {
                                        $(stylisthub_downloadable_product_div).show();
                                      
                                         $('stylisthub_shipping').hide();
                                    }
                                    else {
                                        $(stylisthub_downloadable_product_div).hide();
                                    }
                                }
                                function checkTextarea() {
                                    var nicE = new nicEditors.findEditor('description');
                                    var question = nicE.getContent();
                                    if (question == '') {
                                        $('description').show();
                                        $('description').setStyle({
                                            'width': '529px',
                                            'margin-top': '-140px',
                                            'border': 'none !important',
                                            'background': 'none !important',
                                            'padding': '0px',
                                            'position': 'absolute',
                                            'z-index': '-1'
                                        });

                                    }
                                    var nicE = new nicEditors.findEditor('short_description');
                                    var question = nicE.getContent();
                                    if (question == '') {
                                        $('short_description').show();
                                        $('short_description').setStyle({
                                            'width': '529px',
                                            'margin-top': '-140px',
                                            'border': 'none !important',
                                            'background': 'none !important',
                                            'padding': '0px',
                                            'position': 'absolute',
                                            'z-index': '-1'
                                        });

                                    }
                                }

</script>

<!--  Product SKU available or not  -->
<script type="text/javascript">
    $('sku').observe('keyup', function(event) {    	
        var inputsku = $('sku').getValue();
        var sku = inputsku.length;
        if (sku === 0) {
            $('empty-text').setStyle({display: 'block'});
            $('available').setStyle({display: 'none'});
            $('not-available').setStyle({display: 'none'});
        } else {
        	$('category-loading').setStyle({display:'block'});
            new Ajax.Request("<?php echo Mage::getBaseUrl(); ?>stylisthub/product/checksku/", {
                method: "get",
                parameters: {sku: inputsku},
                onSuccess: successFunc
            });
        }
    });
    function successFunc(response) {    	
        var content = response.responseText;
        if (content == 0) {
        	$('category-loading').setStyle({display:'none'});
            $('available').setStyle({display: 'block'});
            $('not-available').setStyle({display: 'none'});
            $('empty-text').setStyle({display: 'none'});
        }
        else {
        	$('category-loading').setStyle({display:'none'});
            $('available').setStyle({display: 'none'});
            $('not-available').setStyle({display: 'block'});
            $('empty-text').setStyle({display: 'none'});
        }
    }
</script>
<!-- Special from date picket -->
<script type="text/javascript">
    //<![CDATA[
    Calendar.setup({
        inputField: "special_from_date",
        ifFormat: "%m/%e/%Y",
        showsTime: false,
        button: "special_from_date_trig",
        align: "Bl",
        singleClick: true
    });
    //]]>
</script> 

<!-- Special to date picket -->
<script type="text/javascript">
    //<![CDATA[
    Calendar.setup({
        inputField: "special_to_date",
        ifFormat: "%m/%e/%Y",
        showsTime: false,
        button: "special_to_date_trig",
        align: "Bl",
        singleClick: true
    });
    //]]>
</script>

<!-- Category child node show/hide -->  
<script type="text/javascript">
    $$('.block-category li.parent ul').each(function(item) {
        item.hide();
    });

    $$('.block-category li.parent > a span').each(function(element) {

        element.observe('click', function(e) {
            e.element().toggleClassName('end-minus', true);
            e.element().toggleClassName('end-plus', true);
            var idd = e.element().up().next('ul');
            Effect.toggle(idd, 'blind', {duration: 0.5});

            e.preventDefault();
        });
    });
</script>

<!-- Multiple image upload -->
<script type="text/javascript">
    var fields = 0;
    function addNewImage() {
        var id = "image" + fields;
        $("stylisthub_image_list").insert("<div class='market_place_add_image'><input type='file' name='" + id + "' /><input type='radio' name='setbase' value ='" + fields + "'/><?php echo $this->__('Set as base image');?><button type='button' class='button' onclick='removeAddedImage(this)' /><span><span><?php echo $this->__('Remove'); ?></span></span></button>");
        fields += 1;
    }
    function removeAddedImage(value) {
        value.up('div').remove();
    }
</script> 

<!-- Product custom option --> 
<script type="text/javascript">
    var customOptionCount = 1;
    var selectSubChildCustomOptionCount = 0;
    function addMarketPlaceCustomOption() {
        var html = $("stylisthub_custom_option_YYY").innerHTML.replace(/XXX/g, customOptionCount);
        var new_html = html.replace(/YYY/g, customOptionCount);
        $("stylisthub_custom_option_list").insert(new_html);
        customOptionCount = customOptionCount + 1;
    }
    function removeMarketPlaceCustomOption(value) {
        value.up('div').remove();
    }
    function changeMarketPlaceCustomOption(value, option_value) {
        var child_html;
        var child_custom_option_value = value.getValue();
        switch (child_custom_option_value) {
            case "field":
            case "area":
                child_html = $("product_option_CCC_type_text").innerHTML.replace(/CCC/g, option_value);
                break;
            case "file":
                child_html = $("product_option_CCC_type_file").innerHTML.replace(/CCC/g, option_value);
                break;
            case "drop_down":
            case "radio":
            case "checkbox":
            case "multiple":
                child_html = $("product_option_CCC_type_select").innerHTML.replace(/CCC/g, option_value);
                break;
            case "date":
            case "date_time":
            case "time":
                child_html = $("product_option_CCC_type_date").innerHTML.replace(/CCC/g, option_value);
                break;
            default :
                child_html = $("product_option_CCC_type_text").innerHTML.replace(/CCC/g, option_value);
        }
        if (value.up('table').nextSiblings('table') != '')
        {
            value.up('table').next('table').remove();
            value.up('div').insert(child_html);
        }
        else
        {
            value.up('div').insert(child_html);
        }
    }
    function addMarketPlaceChildSelectOption(value, sub_option_value) {
        var selectChildCustomOption = $("product_option_CCC_select_AAA").innerHTML.replace(/CCC/g, sub_option_value);
        var new_selectChildCustomOption = selectChildCustomOption.replace(/AAA/g, selectSubChildCustomOptionCount);
        $(value).insert(new_selectChildCustomOption);
        selectSubChildCustomOptionCount = selectSubChildCustomOptionCount + 1;
    }
    function removeMarketPlaceChildSelectOption(value) {
        value.up('tr').remove();
    }
    // Functions for downloadable products    
    var stylisthubDownloadableSampleRow = 0;
    var stylisthubDownloadableLinkRow = 0;

    function addMarketPlaceDownloadableSamplesRow(value) {
        var selectSampleOption = $("stylisthub_download_sample_row_CCC").innerHTML.replace(/CCC/g, stylisthubDownloadableSampleRow);
        $(value).insert(selectSampleOption);
        stylisthubDownloadableSampleRow = stylisthubDownloadableSampleRow + 1;
    }
    function removeMarketPlaceDownloadableSamplesRow(value) {
        value.up('tr').remove();
    }
    function addMarketPlaceDownloadableLinksRow(value) {
        var selectLinkOption = $("stylisthub_download_link_row_CCC").innerHTML.replace(/CCC/g, stylisthubDownloadableLinkRow);
        $(value).insert(selectLinkOption);
        stylisthubDownloadableLinkRow = stylisthubDownloadableLinkRow + 1;
    }
    function removeMarketPlaceDownloadableLinksRow(value) {
        value.up('table').remove();
    }

    // For text editor
    //<![CDATA[
    bkLib.onDomLoaded(function() {
        new nicEditor({iconsPath: '<?php echo $this->getSkinUrl('stylisthub/nicEditorIcons.gif'); ?>'}).panelInstance('description');

    });
    //]]>
    // For text editor
    //<![CDATA[
    bkLib.onDomLoaded(function() {
        new nicEditor({iconsPath: '<?php echo $this->getSkinUrl('stylisthub/nicEditorIcons.gif'); ?>'}).panelInstance('short_description');
    });
    //]]>
</script>
<?php /**
 * stylist shipping script to display national and international shipping price
 */ ?>
<script type="text/javascript">
    $('stylist_shipping').observe('change', function(event) {
        var selected = $('stylist_shipping').select("option[selected]")[0].innerHTML;
        if (selected == 'Shipping Cost') {
            $('shipping_price').setStyle('display:block');
        } else
            $('shipping_price').setStyle('display:none');
    });
</script>