<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */

/**
 * This file is used to display navigation links in "Stylist My Account"
 * 
 * Links displayed are Stylist Dashboard, Manage Products, Orders, Transaction History,
 * My Profile, Contact Admin and Vacation Mode
 */

$loginId = Mage::getSingleton('customer/session')->isLoggedIn();
$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
$getGroupId = Mage::helper('stylisthub')->getGroupId();
$customer = Mage::getSingleton("customer/session")->getCustomer();
$customerStatus = $customer->getCustomerstatus();
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo Mage::helper('stylisthub')->__('Market Place') ?></span></strong>
    </div>
    <div class="block-content">
        <?php if ($groupId == $getGroupId && $loginId && $customerStatus != 2 && $customerStatus != 0) { ?>
            <ul>
                <?php 
                /*
                * For stylists               
                */?>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->dashboardUrl()) { ?>active<?php } ?>"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->dashboardUrl(); ?>"><?php echo $this->__('Stylist Dashboard'); ?></a></li>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->getManageProductUrl() || Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->getNewProductUrl()) { ?>active<?php } ?>"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->getManageProductUrl() ?>"> <?php echo $this->__('Manage Products') ?> </a></li>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->getManageOrderUrl()) { ?>active<?php } ?>"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->getManageOrderUrl(); ?>"> <?php echo $this->__('Orders') ?> </a></li>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->getViewtransaction()) { ?>active<?php } ?>"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->getViewtransaction(); ?>"> <?php echo $this->__('Transaction History') ?> </a></li>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->addprofileUrl()) { ?>active<?php } ?>"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->addprofileUrl(); ?>"><?php echo $this->__('My Profile') ?></a></li>
                <?php if (Mage::getStoreConfig('stylisthub/admin_approval_stylist_registration/contact_admin') == 1) { ?>
                    <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->getContactFormUrl()) { ?>active<?php } ?>"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->getContactFormUrl(); ?>"> <?php echo $this->__('Contact Admin') ?> </a></li>
                <?php } ?>
                <?php if (Mage::getStoreConfig('superdeals/superdeals_group/deals_enable') == 1) { ?>
                    <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->getManageDealsUrl()) { ?>active<?php } ?>"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->getManageDealsUrl(); ?>"> <?php echo $this->__('Manage Deals') ?> </a></li>
                <?php } ?>
                <?php if (Mage::getStoreConfig('stylisthub/admin_approval_stylist_registration/vacation_mode') == 1) { ?>
                    <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->getVacationModeUrl()) { ?>active<?php } ?> last"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->getVacationModeUrl(); ?>"> <?php echo $this->__('Vacation Mode') ?> </a></li>
                <?php } ?>
            </ul>
        <?php } else { ?>
            <ul>
               <?php 
                /*
                * For Buyers               
                */?>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->becomemerchantUrl()) { ?>active<?php } ?>"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->becomemerchantUrl(); ?>"> <?php echo $this->__('Become a Stylist') ?> </a></li>
                <li class="<?php if (Mage::helper('core/url')->getCurrentUrl() == Mage::helper('stylisthub/stylisthub')->customerreviewUrl()) { ?>active<?php } ?> last"><a href="<?php echo Mage::helper('stylisthub/stylisthub')->customerreviewUrl(); ?>"> <?php echo $this->__('Stylist Reviews') ?> </a></li>
            </ul>
        <?php } ?>
    </div>
</div>