<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */
?>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>stylisthub/nicEdit.js" type="text/javascript"></script>
<script type="text/javascript">
    document.observe("dom:loaded", function() {
        // initially hide all containers for payment details
        $('errormsg').hide();
        if (document.getElementById('bank_pay').checked) {
            $$('#paypal_id').invoke('hide');
            
        } else {
            $$('#bank_payment').invoke('hide');
        }

    });
</script>
<div id="errormsg"></div>
<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $stylistData = Mage::getSingleton('customer/session')->getCustomer();
    $stylistId = $stylistData->getId();
    $profileData = $this->editprofile($stylistId);
}
?>
<div class="page-title">
    <h1><?php echo $this->__('My Profile'); ?></h1>
</div>
<form action="<?php echo $this->addprofile(); ?>" method="post"  id="addprofile"   enctype="multipart/form-data"> 
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Profile Information'); ?></h2>
        <ul class="form-list">
            <!-- stylist id -->
            <input type="hidden" name="stylist_id" id="stylist_id" value="<?php echo $stylistId; ?>"/>      
            <!-- Store Name -->
            <li class="fields">          
                <div class="field">
                    <label for="store_name" class="required">  <?php echo $this->__('Store Name'); ?> <em><?php echo $this->__('*'); ?></em> </label>
                    <div class="input-box"><input type="text" name="store_name" id="store_name" value="<?php echo $profileData['store_title']; ?>" class="input-text required-entry" /></div> 
                </div>               
            </li>
             <?php 
             /**
              * For future enhancement
              */
             ?>
<!--            <li class="fields">
            <div>
                    Country
                    <label for="country"><?php //echo $this->__('Country'); ?>  </label>  
                    <?php
                    //$_countries = Mage::getResourceModel('directory/country_collection')
                           // ->loadData()
                           // ->toOptionArray(false)
                    ?>
                            <?php //if (count($_countries) > 0) { ?>
                        <select name="country" id="country" class="validate-select" title="Country" >
                            <option value="">-- Please Select --</option>
                            <?php //foreach ($_countries as $_country) { ?>
                                <option value="<?php //echo $_country['value']; ?>" <?php //echo $profile_data['country'] == $_country['value'] ? ' selected="selected"' : ''; ?>>
                            <?php //echo $_country['label'] ?>
                                </option>
                            <?php //} ?>
                        </select>
                    <?php //} ?>
                </div>                 
            </li> -->
            <li class="fields">
                    <label for="contact" class="required"><?php echo $this->__('Contact Number'); ?> <em><?php echo $this->__('*'); ?></em>   </label>
                    <div class="input-box"><input type="text" name="contact" id="contact" value="<?php echo $profileData['contact']; ?>" class="validate-phoneLax input-text required-entry" /></div> 
            </li>
	<?php 
	/**
	 * Description
	 */
	?>
               
            <li class="wide fields">
                <div>
                    <label for="description"><?php echo $this->__('Description'); ?>  </label>
                    <div class="input-box"> <textarea name="description" rows="10" cols="75" id="description" class="validate-length maximum-length-255 textarea"/><?php echo $profileData['description']; ?></textarea>
                    </div>
                </div>
            </li>
           <?php 
           /**
            * Store Logo
            */
           ?>
           
            <li class="fields">
                <div class="field_store_logos">
                    <label for="store_logo"><?php echo $this->__('Store Logo'); ?>  </label>                    
                    <div class="store_logos">
                    <input type="file" name="store_logo" id="store_logo" onchange="return validateFileExtension(this);"/>
                    <div class="clear"></div>  
                    <span class="market_place_image_sizes"><?php echo $this->__('Upload image size 95 X 62'); ?></span>
                    <div style="clear:both;"></div>                  
                        <?php if (strpos($profileData['store_logo'], '.') && !empty($profileData['store_logo'])) { ?>
                        <img src="<?php echo Mage::getBaseUrl('media') . "stylisthub/resized/" . $profileData['store_logo']; ?>" alt="store logo" class="store_img"/>
                        <div style="clear:both;"></div>
                    	<input type="checkbox" name="remove" value="1"> <?php echo $this->__('Remove'); ?>
                    <?php } ?>                        
                    </div>            
                </div>
            </li>
            <?php 
            /**
             * For future enhancement
             */
            ?>
<!--            Twitter Id 
            <li class="fields">
                <div class="field">         
                    <label for="twitter_id" class="required"><?php //echo $this->__('Twitter Id'); ?></label>
                    <div class="input-box"><input type="text" name="twitter_id" id="twitter_id" value="<?php //echo $profile_data['twitter_id']; ?>" class="input-text"/>
                    <?php// echo 'Ex: https://www.twitter.com/example'; ?>
                    </div>                    
                </div>
            </li>
            <li class="fields">
                Facebook Id 
                <div class="field">       
                    <label for="facebook_id" class="required"><?php //echo $this->__('Facebook Id'); ?></label>
                    <div class="input-box"><input type="text" name="facebook_id" id="facebook_id" value="<?php //echo $profile_data['facebook_id']; ?>" class="input-text"/>
                    <?php //echo 'Ex: https://www.facebook.com/example'; ?>
                    </div>                    
                </div> 
            </li>             -->
            <?php 
            /**
             * Meta Keyword
             */
            ?>
          
            <li class="fields">  
                <div class="field">       
                    <label for="meta_keyword" class="required"> <?php echo $this->__('Meta Keyword'); ?>  </label>
                    <div class="input-box"> 
                        <textarea id="meta_keyword" name="meta_keyword"  rows="5" cols="60" class="input-text"><?php echo $profileData['meta_keyword']; ?></textarea></br></br>
                    </div>
                </div>
                <?php 
                /**
                 * Meta Description
                 */
                ?>
             
                <div class="field">       
                    <label for="meta_description" class="required"><?php echo $this->__('Meta Description'); ?>  </label>
                    <div class="input-box"> 
                        <textarea id="meta_description" name ="meta_description"  rows="5" cols="60" class="input-text"><?php echo $profileData['meta_description']; ?></textarea></br></br>
                    </div>
                </div>
            </li>
            <?php 
            /**
             * Payment Details
             */
            ?>
           
            <li class="fields">   
                <label class="payment_hint"><?php echo $this->__('Process Payment via Bank/Paypal Account'); ?></label>
                <div class="field payment-snipt"> 
                    <div class="input-box market_place_payment_process"> 
                        <input type="radio" name="bank" id="bank_pay" class="radio" value="bankpayment" onclick="payment();" <?php if ($profileData['bank_payment']) { ?> checked="checked" <?php } ?>> <label class="required" style="float: none;"><?php echo $this->__('Bank Payment'); ?> </label>
                        <textarea name="bank_payment" id="bank_payment" class="input-text"><?php echo $profileData['bank_payment']; ?></textarea>
                    </div>
                    <div class="clear"></div>
                    <div class="input-box market_place_payment_process">                         
                        <input type="radio" name="bank" id="paypal_pay" class="radio" value="paypal" onclick="payment();" <?php if ($profileData['paypal_id']) { ?> checked="checked" <?php } ?>> <label class="required" style="float: none;"></em> <?php echo $this->__('Paypal Id'); ?> </label>
                        <input type="text" name="paypal_id" id="paypal_id" value="<?php echo $profileData['paypal_id']; ?>" class="input-text validate-email"/>
                    </div>  
                </div>   
            </li> 
            
        </ul>
    </div>
    <?php 
    /**
     * Submit button 
     */
    ?>
   
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p> 
        <input type="checkbox" name="show_profile" value="1"  <?php if ($profileData['show_profile'] == 1) { ?> checked="checked" <?php } ?>> <?php echo $this->__('Display your profile link in product detail page'); ?>
        <button type="submit" class="button"  title="<?php echo $this->__('Save Profile') ?>" name="save_profile" id="save_profile" ><span><span><?php echo $this->__('Save Profile') ?></span></span></button>   
    </div>    
</form>  
<?php 
/**
 * Form validation script
 */
?>

<script type="text/javascript">
    var dataForm = new VarienForm('addprofile');
    function payment() {
        if (document.getElementById('bank_pay').checked) {
            document.getElementById('bank_payment').show();
            document.getElementById('paypal_id').hide();
        } else if (document.getElementById('paypal_pay').checked) {
            document.getElementById('paypal_id').show();
            document.getElementById('bank_payment').hide();
        }
    }
    function validateFileExtension(fld) {
        if (!/(\.bmp|\.png|\.gif|\.jpg|\.jpeg)$/i.test(fld.value)) {
            fld.form.reset();
            fld.focus();
            $('errormsg').show();
            document.getElementById("errormsg").innerHTML = "Invalid file format";
            return false;
        }
        return true;
    }
//<![CDATA[
    bkLib.onDomLoaded(function() {
        new nicEditor({iconsPath: '<?php echo $this->getSkinUrl('stylisthub/nicEditorIcons.gif'); ?>'}).panelInstance('description');
    });
    //]]>
</script>