<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */
?>
<?php
//Get stylist id from url
$id = $this->getRequest()->getParam('id');

//Stylist data collection to display stylist store name
$stylistData = Mage::getModel('stylisthub/stylistreview')->getStylistInfo($id);

//Stylist review collection
$displayReview = $this->getCollection();
if (count($displayReview) > 0) {
    ?>
    <h3><?php echo $this->__('Reviews and Ratings of %s', $stylistData); ?> </h3> 
    <?php
    foreach ($displayReview as $_displayReview) {
        $cus_id = $_displayReview['customer_id'] . '</br>';
        $customerData = Mage::getModel('customer/customer')->load($cus_id)->getData();
        ?>
        <div class="all_review_container">   
            <div class="all_reviews_details">
                <p class="all_reviews_block">
                    <?php
                    //Display stylist rating
                    if ($_displayReview['rating'] == 1) {
                        ?>
                        <label class="all_review_rating" style="width:20%;"></label>
                    <?php } elseif ($_displayReview['rating'] == 2) { ?>
                        <label class="all_review_rating" style="width:40%;"></label>
                    <?php } elseif ($_displayReview['rating'] == 3) { ?>
                        <label class="all_review_rating" style="width:60%;"></label>
                    <?php } elseif ($_displayReview['rating'] == 4) { ?>
                        <label class="all_review_rating" style="width:80%;"></label>
                    <?php } else { ?>
                        <label class="all_review_rating" style="width:100%;"></label>
                    <?php } ?>   
                </p>
                <b><?php echo $customerData['firstname'] . '</br>'; ?></b>                 
                <span>
                    <?php $date = $_displayReview['created_at'];
                    echo $new_date = date('M j, Y', strtotime($date)) . '</br>';
                    ?>               
                </span>
            </div> 
            <p class="all_reviews_comments">
        <?php echo $_displayReview['review'] . '</br>'; ?> 
            </p>
        </div>
        <div class="clear"></div>
        <?php
    }
}

// Display pagination
echo $this->getPagerHtml();

//Checking whether stylist review enabled by admin
$active = Mage::getStoreConfig('stylisthub/admin_approval_stylist_registration/displayproductpage');
if ($active == 1) {
    $url = Mage::getModel('stylisthub/stylistreview')->backUrl($id);
}
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customer_id = Mage::getSingleton('customer/session')->getId();
    $orders = Mage::helper('stylisthub/stylisthub')->allowReview($customer_id);
    $order_id = $orders->getFirstItem()->getId();
    $end_date = $orders->getFirstItem()->getCreatedAt();
    $current_date = Mage::getModel('core/date')->date('Y-m-d H:i:s');
    $days = abs(strtotime($current_date) - strtotime($end_date));
    $years = floor($days / (365 * 60 * 60 * 24));
    $months = floor(($days - $years * 365 * 60 * 60 * 24) / (30 * 60 * 60 * 24));
    $diff = floor(($days - $years * 365 * 60 * 60 * 24 - $months * 30 * 60 * 60 * 24) / (60 * 60 * 24));
    $order = Mage::getModel('sales/order')->load($order_id);
    $items = $order->getAllItems();
    $getitem = array_slice($items, -1, 1, true);
    foreach ($getitem as $item) {
        $product_id = $item->getProductId();
        $products = Mage::getModel('catalog/product')->load($product_id);
        $product_stylist = $products->getStylistId();
        $checkReview = Mage::getModel('stylisthub/stylistreview')->checkReview($customer_id, $id, $product_id);
        if ($diff <= 30 && $product_stylist == $id && $checkReview == '') {
            //Stylist Review form
            if (Mage::getSingleton('customer/session')->isLoggedIn()) {
                $logged_customer_id = Mage::getSingleton('customer/session')->getId();
                $customer = Mage::getSingleton('customer/session')->getCustomer();
                $customer_name = $customer->getName();
                $id = $this->getRequest()->getParam('id');
                $customer_id = $this->getRequest()->getParam('cus');
                $product_id = $this->getRequest()->getParam('product');
                if ($id && ($customer_id == $logged_customer_id) && $product_id) {
                    ?>                    
                    <div class="mp_rate_feedback"><h3 class="home_pdt_name"><span><?php echo $this->__('Rate and leave feedback for stylist store'); ?></span></h3>
                        <!--<h4><?php echo $this->__('Item Bought'); ?></h4>-->  
                        <p class="mp_stylist_product">
                            <a href="<?php echo $products->getProductUrl(); ?>">
                                <span><?php $products = Mage::getModel('catalog/product')->load($product_id);
                    echo $products->getName();
                    ?>
                                </span>
                                <img src="<?php echo Mage::helper('catalog/image')->init($products, 'image')->resize(250, 250); ?>" alt="" />
                            </a>
                        </p>
                        <div class="mp_stylist_rating">
                            <form action='<?php echo $this->saveReviewUrl(); ?>'id="stylist_review" method="post" >                                
                                <p class="mp_stylist_comments">
                                    <label for="stylistname"> <?php echo $this->__('Name:'); ?>  </label>
                                    <input type="text" value="<?php echo $customer_name; ?>" readonly />
                                </p>
                                <p class="mp_stylist_comments">
                                    <label for="feedback"> <?php echo $this->__('Feedback about stylist:'); ?>  </label>
                                    <textarea id="feedback" rows="9" cols="49" name="feedback" class="input-text required-entry"></textarea>
                                </p>
                                <input type="hidden" name="stylist_id" value="<?php echo $id; ?>"/>
                                <input type="hidden" name="customer_id" value="<?php echo $customer_id; ?>"/>
                                <input type="hidden" name="product_id" value="<?php echo $product_id; ?>"/>
                                <label class="mp_stylist_left" for="rating"><?php echo $this->__('Rate Stylist:'); ?>  </label>
                                <ul class="mp_stylist_rate_options">
                                    <li class="user-rating" id="set-user-rating"></li>
                                    <li><input type="radio" id="rate1" name="rating" value="1" class="validate-one-required" style="display:none;" ><a href="javascript:void(0);" class="rate-1" onclick="setRating(1);"></a></li>
                                    <li><input type="radio" id="rate2" name="rating" value="2" class="validate-one-required" style="display:none;"><a href="javascript:void(0);" class="rate-2" onclick="setRating(2);"></a></li>
                                    <li><input type="radio" id="rate3" name="rating" value="3" class="validate-one-required" style="display:none;"><a href="javascript:void(0);" class="rate-3" onclick="setRating(3);"></a></li>
                                    <li><input type="radio" id="rate4" name="rating" value="4" class="validate-one-required" style="display:none;"><a href="javascript:void(0);" class="rate-4" onclick="setRating(4);"></a></li>
                                    <li><input type="radio" id="rate5" name="rating" value="5" class="validate-one-required" style="display:none;"><a href="javascript:void(0);" class="rate-5" onclick="setRating(5);"></a></li>
                                </ul>   
                                <br />
                                <button type="submit" class="button"  title="<?php echo $this->__('Submit Review') ?>" name="submit_review" id="submit_review" ><span><span><?php echo $this->__('Submit') ?></span></span></button> 
                            </form>
                        </div>
                        <div class="clear"></div>                        
                    </div>
                    <?php
                }
            }
        }
    }
}

//Display back button
$url = Mage::getModel('stylisthub/stylistreview')->backUrl($id);
?>
<a href="<?php echo $url; ?>"><?php echo $this->__('Back'); ?></a>
<script type="text/javascript">
    var dataForm = new VarienForm('stylist_review');
    function setRating(value) {
        SetWidth = (value * 20) + '%';
        $('set-user-rating').setStyle({width: SetWidth});
        $('rate' + value).checked = true;
    }
</script>