<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */
?>
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
    <h2> <?php echo $this->__('Stylist Reviews'); ?></h2>
    <?php
    $collection = $this->getCollection();
    if (count($collection) > 0) {
        foreach ($collection as $_collection) {
            ?>
            <div class="all_review_container">   
                <div class="all_reviews_details">
                    <p class="all_reviews_block">
                        <?php
                        $id = $_collection['stylist_id'];
                        $store_name = Mage::getModel('stylisthub/stylistreview')->getStylistInfo($id);

                        //Display stylist rating
                        if ($_collection['rating'] == 1) {
                            ?>
                            <label class="all_review_rating" style="width:20%;"></label>
                        <?php } elseif ($_collection['rating'] == 2) { ?>
                            <label class="all_review_rating" style="width:40%;"></label>
                        <?php } elseif ($_collection['rating'] == 3) { ?>
                            <label class="all_review_rating" style="width:60%;"></label>
                        <?php } elseif ($_collection['rating'] == 4) { ?>
                            <label class="all_review_rating" style="width:80%;"></label>
                        <?php } else { ?>
                            <label class="all_review_rating" style="width:100%;"></label>
            <?php } ?>   
                    </p>
                    <b><?php echo $store_name . '</br>'; ?></b>                 
                    <span>
                        <?php $date = $_collection['created_at'];
                        echo $new_date = date('M j, Y', strtotime($date)) . '</br>';
                        ?>               
                    </span>
                </div> 
                <p class="all_reviews_comments">
            <?php echo $review = $_collection['review'] . '</br>'; ?> 
                </p>
            </div>
        <?php
        }
        echo $this->getPagerHtml();
    } else {
        echo $this->__('You have not review any stylist');
    }
}
?>
