<?php
/**
 * SMD
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magemobiledesign.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * SMD does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * SMD does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    SMD
 * @package     SMD_Stylisthub
 * @version     1.2.3
 * @author      SMD Team <support@magemobiledesign.com>
 * @copyright   Copyright (c) 2014 SMD. (http://www.magemobiledesign.com)
 * @license     http://www.magemobiledesign.com/LICENSE.txt
 * 
 */
/**
 * This file contains stylist vacation mode functionality
 */

    $vacationInfo = $this->loadVactionInfo();
    ?>
    <div class="page-title">
        <h1><?php echo $this->__('My Vacation'); ?></h1>
    </div>
    <form method="post" name="vacation_mode" id="vacation_mode" action="<?php echo Mage::helper('stylisthub/stylisthub')->getVacationModeSaveUrl(); ?>"> 
      <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Vacation Configuration'); ?></h2>
        <ul class="form-list">        
            <li class="fields">          
                <div class="field">
                    <label for="vacation_status" class="required"><?php echo $this->__('Vacation Status'); ?><em><?php echo $this->__('*'); ?></em></label>                    
                    <div class="input-box">
                        <input type="radio" class="validate-one-required-by-name" name="vacation_status" value="0" <?php if (isset($vacationInfo['vacation_status']) && $vacationInfo['vacation_status'] == 0) { ?> checked <?php } ?>/><?php echo $this->__('YES')?>
                        <input type="radio" class="validate-one-required-by-name" name="vacation_status" value="1" <?php if (isset($vacationInfo['vacation_status']) && $vacationInfo['vacation_status'] == 1) { ?> checked <?php } ?>/><?php echo $this->__('NO')?> <br/>
                    </div> 
                </div>               
            </li>
            <li class="fields">          
                <div class="field">
                    <label for="vacation_message" class="required"><em>*</em><?php echo $this->__('Vacation Message'); ?></label>
                    <div class="input-box">
                        <textarea rows="10" cols="30" name="vacation_message" id="vacation_message" class="input-text required-entry"><?php echo $vacationInfo['vacation_message']; ?></textarea><br/>
                    </div>
                </div>
            </li>
            <li class="fields">          
                <div class="field">
                    <label for="disable_products" class="required"><em>*</em><?php echo $this->__('Disable Products'); ?></label>
                    <div class="input-box">
                        <input type="radio" class="validate-one-required-by-name" name="disable_products" value="0" <?php if (isset($vacationInfo['product_disabled']) && $vacationInfo['product_disabled'] == 0) { ?> checked <?php } ?>/><?php echo $this->__('YES')?>
                        <input type="radio" class="validate-one-required-by-name" name="disable_products" value="1" <?php if (isset($vacationInfo['product_disabled']) && $vacationInfo['product_disabled'] == 1) { ?> checked <?php } ?>/><?php echo $this->__('NO')?> <br/>   
                    </div>
                </div>
            </li>
            <li class="fields">          
                <div class="field">
                    <label for="date_from" class="required"><em>*</em><?php echo $this->__('From Date'); ?></label>
                    <div class="input-box">
                        <input type="text" name="date_from" class="required-entry validate-date validate-date-range date-range-date-from" id="date_from" value="<?php if(isset($vacationInfo['date_from']) && $vacationInfo['date_from']!=''){ echo date('m/d/Y', strtotime($vacationInfo['date_from'])); } ?>" />
                        <img src="<?php echo $this->getSkinUrl("images/calendar.gif"); ?>" alt="" class="v-middle" id="special_from_date_trig" title="<?php echo $this->__('Select Date'); ?>" style="" />
                    </div>
                </div>
            </li>
            <li class="fields vacation_enddate">          
                <div class="field">
                    <label for="date_to" class="required"><em>*</em><?php echo $this->__('To Date'); ?></label>    
                    <div class="input-box">    
                        <input type="text" name="date_to" class="required-entry validate-date validate-date-range date-range-date-to" id="date_to" value="<?php if(isset($vacationInfo['date_to']) && $vacationInfo['date_to']!='') { echo date('m/d/Y', strtotime($vacationInfo['date_to'])); } ?>" />
                        <img src="<?php echo $this->getSkinUrl("images/calendar.gif"); ?>" alt="" class="v-middle" id="special_to_date_trig" title="<?php echo $this->__('Select Date'); ?>" style="" />                                                
                    </div>
                </div>
            </li>
        </ul>
      </div>
        <!--Submit button -->
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p> 
        <button type="submit" class="button vacation_btn"  title="<?php echo $this->__('Submit') ?>" name="submit" id="submit" ><span><span><?php echo $this->__('Submit') ?></span></span></button>   
    </div> 
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('vacation_mode');
        // <![CDATA[
        Calendar.setup({
            inputField: 'date_from',
            ifFormat: '%m/%e/%y',
            button: 'special_from_date_trig',
            align: 'Bl',
            singleClick: true
        });

        Calendar.setup({
            inputField: 'date_to',
            ifFormat: '%m/%e/%y',
            button: 'special_to_date_trig',
            align: 'Bl',
            singleClick: true
        });
        // ]]>
    </script>
